version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REGISTRY: 008041186656.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_REPO_NAME: ruberoo-config
    IMAGE_TAG: latest
    SERVICE_NAME: ruberoo-config-server

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - REPOSITORY_URI=$ECR_REGISTRY/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Build started on `date`
  build:
    commands:
      - echo Building the Docker image...
      - cd $SERVICE_NAME
      - mvn clean package -DskipTests
      - cd ..
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG -f $SERVICE_NAME/Dockerfile $SERVICE_NAME
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"name":"config-server","imageUri":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

