apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ruberoo
type: Opaque
stringData:
  # Spring property: jwt.secret-key -> environment variable JWT_SECRET_KEY
  # Using stringData allows us to put the plaintext Base64 token here without double-encoding.
  secret-key: "VM14Gy7IZ6x5S/82gZ2CXBtY7+6YjU210Q62RaNvYhF4ociVnWNzhSvv/loEpd5YYEUgzBHsmVVmgFdMokAn7w=="

