apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: ruberoo
type: Opaque
stringData:
  RDS_HOST: ruberoo-mysql.cq382ua6uclq.us-east-1.rds.amazonaws.com
  RDS_PORT: "3306"
  RDS_USERNAME: admin
  RDS_PASSWORD: Ruberoo&121619

