server:
  port: 8888 # Standard port for Config Server

spring:
  application:
    name: CONFIG-SERVER # Register with Eureka under this name
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mitali246/ruberoo-microservices.git
          default-label: main

eureka:
  client:
    service-url:
      # Point to your running Eureka Server instance
      defaultZone: http://localhost:8761/eureka