server:
  port: 8888 # Standard port for Config Server

spring:
  application:
    name: CONFIG-SERVER # Register with Eureka under this name
  cloud:
    config:
      server:
        git:
          # IMPORTANT: Replace <YOUR_GITHUB_CONFIG_REPO_URL> with the actual HTTPS URL
          # to your existing 'ruberoo-config' GitHub repository.
          uri: https://github.com/mitali246/ruberoo-microservices.git
          # If you don't use 'main', specify your branch name here:
          default-label: main

eureka:
  client:
    service-url:
      # Point to your running Eureka Server instance
      defaultZone: http://localhost:8761/eureka